<?php

/**
 * @file
 * Provides a caption textarea for image fields.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\image_field_caption\ImageCaptionStorage;

// @todo Support for Views, maybe built in in D8?
// @todo Support the revision management.

/**
 * Implements hook_field_info_alter().
 */
function image_field_caption_field_info_alter(&$info) {
  // Set a new class for the image fields.
  $info['image']['class'] = '\Drupal\image_field_caption\ImageCaptionItem';
}

/**
 * Implements hook_form_FORM_ID_alter() for 'field_config_edit_form'.
 */
function image_field_caption_form_field_config_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Get the entity.
  $entity = $form_state->getFormObject()->getEntity();
  // Check if the field is an image field.
  if ($entity->get('field_type') == 'image') {
    // Adds new submit callback function.
    $form['actions']['submit']['#submit'][] = '_image_field_caption_form_field_config_edit_submit';
  }
}

/**
 * Custom form submit callback for 'field_config_edit_form'.
 */
function _image_field_caption_form_field_config_edit_submit($form, FormStateInterface $form_state) {
  // Get the entity.
  $entity = $form_state->getFormObject()->getEntity();
  // Save the field settings related to the caption.
  $field_storage = Drupal::entityTypeManager()->getStorage('field_config')->load($entity->get('entity_type') . '.' . $entity->get('bundle') . '.' . $entity->get('field_name'));
  if (!empty($field_storage)) {
    // Get form values.
    $values = $form_state->getValues();
    // Set and save settings.
    $field_storage->setSetting('caption_field', $values['settings']['image_caption_field']);
    $field_storage->setSetting('caption_field_required', $values['settings']['image_caption_field_required']);
    $field_storage->save();
  }
  else {
    // Set message text.
    $message = t('Unable to load the field config of the %field_name field.', array(
      '%field_name' => $entity->get('entity_type') . '.' . $entity->get('bundle') . '.' . $entity->get('field_name'),
    ));
    // Add user message.
    drupal_set_message($message, 'error');
    // Add log entry.
    Drupal::logger('image_field_caption')->error($message);
  }
}

/**
 * Implements hook_field_widget_form_alter().
 */
function image_field_caption_field_widget_form_alter(&$element, FormStateInterface $form_state, $context) {
  // Get the current field definition.
  $field = $context['items']->getFieldDefinition();
  // If the current field is an image field.
  if ($field->getType() == 'image') {
    // Get the current field settings.
    $settings = $field->getSettings();
    // Check if the current field has the caption.
    if (!empty($settings['caption_field'])) {
      $element['#process'][] = '_image_field_caption_widget_process';
    }
  }
}

/**
 * Custom callback function for the #process of an image field type.
 */
function _image_field_caption_widget_process($element, &$form_state, $form) {
  // Get the entity.
  $entity = $form_state->getFormObject()->getEntity();
  // Get the fields definitions.
  $field_definitions = $entity->getFieldDefinitions();
  // Get the current field definition.
  $field_definition = (!empty($field_definitions[$element['#field_name']])) ? $field_definitions[$element['#field_name']] : NULL;
  // Get the current field settings.
  $settings = array();
  if (!empty($field_definition)) {
    $settings = $field_definition->getSettings();
  }
  // Get the current field values (form state).
  $field_values = $form_state->getValues();
  $field_value = (isset($field_values[$element['#field_name']][$element['#delta']]['image_field_caption'])) ? $field_values[$element['#field_name']][$element['#delta']]['image_field_caption'] : array();
  // Add the additional caption fields.
  $element['image_field_caption'] = array(
    '#title' => t('Caption'),
    '#type' => 'text_format',
    '#default_value' => (!empty($element['#value']['caption'])) ? $element['#value']['caption'] : '',
    '#access' => (bool) $element['#value']['fids'],
    '#format' => (!empty($field_value['format'])) ? $field_value['format'] : ((!empty($element['#value']['caption_format'])) ? $element['#value']['caption_format'] : NULL),
    '#value' => (!empty($field_value['value'])) ? $field_value['value'] : ((!empty($element['#value']['caption'])) ? $element['#value']['caption'] : NULL),
    '#required' => (!empty($settings['caption_field_required'])) ? TRUE : FALSE,
  );
  return $element;
}

/**
 * Implements hook_theme().
 */
function image_field_caption_theme() {
  return array(
    'image_caption_formatter' => array(
      // As we extend the default image format, the variables passed to the callback function
      // are the same than the original "callback" function ("image_formatter").
      'variables' => array('item' => NULL, 'item_attributes' => NULL, 'url' => NULL, 'image_style' => NULL),
    ),
  );
}

/**
 * Prepares variables for image caption formatter templates.
 *
 * Default template: image-caption-formatter.html.twig.
 *
 * @param array $variables
 *   An associative array containing all values from the original function (template_preprocess_image_formatter())
 *   and also:
 *   - caption: An optional caption text.
 */
function template_preprocess_image_caption_formatter(&$variables) {
  // Prepare the variables array with the original function.
  template_preprocess_image_formatter($variables);
  // Set the caption value.
  $values = $variables['item']->getValue();
  if (!empty($values['caption'])) {
    $variables['caption'] = $values['caption'];
  }
}

/**
 * Implements hook_entity_load().
 */
function image_field_caption_entity_load(array $entities, $entity_type_id) {
  foreach ($entities as $entity) {
    // For a fieldable entity.
    if (($entity instanceof FieldableEntityInterface)) {
      // Get the field names of all image fields.
      $field_names = _image_field_caption_get_image_field_names($entity);
      foreach ($field_names as $field_name) {
        // Load all values for this field.
        $values = $entity->get($field_name)->getValue();
        foreach ($values as $delta => $value) {
          // Get the caption associated to this field.
          $revision_id = (empty($entity->getRevisionId()) ? $entity->id() : $entity->getRevisionId());
          $caption = ImageCaptionStorage::getCaption(
            $entity->getEntityTypeId(),
            $entity->bundle(),
            $field_name,
            $entity->id(),
            $revision_id,
            $entity->language()->getId(),
            $delta
          );
          // Set the caption value.
          if (!empty($caption)) {
            $values[$delta] = $values[$delta] + $caption;
          }
        }
        // Save all values.
        $entity->get($field_name)->setValue($values);
      }
    }
  }
}

/**
 * Implements hook_entity_insert().
 */
function image_field_caption_entity_insert(EntityInterface $entity) {
  image_field_caption_entity_update($entity);
}

/**
 * Implements hook_entity_update().
 */
function image_field_caption_entity_update(EntityInterface $entity) {
  // For a fieldable entity.
  if (($entity instanceof FieldableEntityInterface)) {
    // Get the field names of all image fields.
    $field_names = _image_field_caption_get_image_field_names($entity);
    foreach ($field_names as $field_name) {
      // Get the current field settings.
      $settings = $entity->get($field_name)->getSettings();
      // If the caption is not enabled => pass this field.
      if (empty($settings['caption_field'])) {
        continue;
      }
      // Delete the caption associated to this field.
      ImageCaptionStorage::deleteCaption($entity->getEntityTypeId(), $entity->bundle(), $field_name, $entity->id(), $entity->language()->getId());
      // Delete the caption revision associated to this field.
      /*
      ImageCaptionStorage::deleteCaptionRevision($entity->getEntityTypeId(), $entity->bundle(), $field_name, $entity->id(), $entity->getRevisionId(), $entity->language()->getId());
      */
      // Get the current field values.
      $values = $entity->get($field_name)->getValue();
      foreach ($values as $delta => $value) {
        // If a caption text is defined.
        if (!empty($value['image_field_caption']['value'])) {
          // Insert the caption associated to this field.
          // @todo Do the insertion using a multiple query instead several queries into a foreach;
          $revision_id = (empty($entity->getRevisionId()) ? $entity->id() : $entity->getRevisionId());
          ImageCaptionStorage::insertCaption(
            $entity->getEntityTypeId(),
            $entity->bundle(),
            $field_name,
            $entity->id(),
            $revision_id,
            $entity->language()->getId(),
            $delta,
            $value['image_field_caption']['value'],
            $value['image_field_caption']['format']
          );
          // Insert the caption revision associated to this field.
          /*
          if ($entity->isNewRevision()) {
            ImageCaptionStorage::insertCaptionRevision(
              $entity->getEntityTypeId(),
              $entity->bundle(),
              $field_name,
              $entity->id(),
              $revision_id,
              $entity->language()->getId(),
              $delta,
              $value['image_field_caption']['value'],
              $value['image_field_caption']['format']
            );
          }
          */
        }
      }
    }
  }
}

/**
 * Implements hook_entity_delete().
 */
function image_field_caption_entity_delete(EntityInterface $entity) {
  // For a fieldable entity.
  if (($entity instanceof FieldableEntityInterface)) {
    // Get the field names of all image fields.
    $field_names = _image_field_caption_get_image_field_names($entity);
    foreach ($field_names as $field_name) {
      // Delete the caption associated to this field.
      ImageCaptionStorage::deleteCaption($entity->getEntityTypeId(), $entity->bundle(), $field_name, $entity->id(), $entity->language()->getId());
      // Delete the caption revisions associated to this field.
      /*
      ImageCaptionStorage::deleteCaptionRevisions($entity->getEntityTypeId(), $entity->bundle(), $field_name, $entity->id(), $entity->language()->getId());
      */
    }
  }
}

/**
 * Implements hook_entity_revision_delete().
 */
function image_field_caption_entity_revision_delete(EntityInterface $entity) {
  /*
  // For a fieldable entity.
  if (($entity instanceof FieldableEntityInterface)) {
    // Get the field names of all image fields.
    $field_names = _image_field_caption_get_image_field_names($entity);
    if (!empty($field_names)) {
      // Delete the caption revisions associated to this specific revision.
      ImageCaptionStorage::deleteCaptionRevisionsByRevisionId($entity->getRevisionId());
    }
  }
  */
}

/**
 * Determines the image fields on an entity.
 *
 * @param \Drupal\Core\Entity\FieldableEntityInterface $entity
 *   An entity whose fields to analyze.
 *
 * @return array
 *   The names of the fields on this entity that support formatted text.
 */
function _image_field_caption_get_image_field_names(FieldableEntityInterface $entity) {
  // Check if fields definitions are available.
  $field_definitions = $entity->getFieldDefinitions();
  if (empty($field_definitions)) {
    return array();
  }
  // Only return image fields.
  return array_keys(array_filter($field_definitions, function (FieldDefinitionInterface $definition) {
    return in_array($definition->getType(), array('image'), TRUE);
  }));
}
